const data = {
    products: [
        {
            _id:'1',
            name: 'Watchmen (Alan Moore)',
            category: 'Books',
            image: '/images/p1.jpg',
            price:25.49,
            countInStock: 10,
            rating:4.8,
            numReviews:40,
            description: "This Hugo Award-winning graphic novel chronicles the fall from grace of a group of super-heroes plagued by all-too-human failings. Along the way, the concept of the super-hero is dissected as the heroes are stalked by an unknown assassin.",
        },
        {
            _id:'2',
            name: 'V for Vendetta (Alan Moore & David Lloyd)',
            category: 'Books',
            image: '/images/p2.jpg',
            price:22.35,
            countInStock: 10,
            rating:4.7,
            numReviews:34,
            description: "high quality product",
        },
        {
            _id:'3',
            name: 'The Walking Dead (Robert Kirkman)',
            category: 'Books',
            image: '/images/p3.jpg',
            price:17.49,
            rating:4.7,
            numReviews:50,
            description: "high quality product",
        },
        {
            _id:'4',
            name: 'The Sandman (Neil Gaiman & others)',
            category: 'Books',
            image: '/images/p4.jpg',
            price:20.00,
            rating:4.6,
            numReviews:32,
            description: "high quality product",
        },
        {
            _id:'5',
            name: 'Maus (Art Spiegelman)',
            category: 'Books',
            image: '/images/p5.jpg',
            price:24.95,
            rating:4.8,
            numReviews:35,
            description: 'high quality product',
        },
        {
            _id:'6',
            name: 'Transmetropolitan (Warren Ellis)',
            category: 'Books',
            image: '/images/p6.jpg',
            price:16.65,
            rating:4.3,
            numReviews:45,
            description: 'high quality product',
        },
        {
            _id:'7',
            name: 'Fables (Bill Willingham)',
            category: 'Books',
            image: '/images/p7.jpg',
            price:17.75,
            rating:4.3,
            numReviews:40,
            description: 'high quality product',
        },
        {
            _id:'8',
            name: 'Preacher (Garth Ennis, Steve Dillon)',
            category: 'Books',
            image: '/images/p8.jpg',
            price:20,
            rating:4.4,
            numReviews:33,
            description: 'high quality product',
        },
        {
            _id:'9',
            name: 'Y: The Last Man (Brian K. Vaughan)',
            category: 'Books',
            image: '/images/p9.jpg',
            price:21.45,
            rating:4.5,
            numReviews:43,
            description: 'high quality product',
        },
        {
            _id:'10',
            name: 'Blankets (Craig Thompson)',
            category: 'Books',
            image: '/images/p10.jpg',
            price:24.45,
            rating:4.5,
            numReviews:34,
            description: 'high quality product',
        },
        {
            _id:'11',
            name: 'Saga (Brian Vaughan & Fiona Staples)',
            category: 'Books',
            image: '/images/p11.jpg',
            price:29.95,
            rating:4.2,
            numReviews:37,
            description: 'high quality product',
        },
        {
            _id:'12',
            name: 'Marvels (Alex Ross and Kurt Busiek)',
            category: 'Books',
            image: '/images/p12.jpg',
            price:25.45,
            rating:4.1,
            numReviews:29,
            description: 'high quality product',
        },
        {
            _id:'13',
            name: 'Scott Pilgrim (Bryan Lee O’Malley)',
            category: 'Books',
            image: '/images/p13.jpg',
            price:26,
            rating:3.9,
            numReviews:26,
            description: 'high quality product',
        },
        {
            _id:'14',
            name: 'Sin City (Frank Miller)',
            category: 'Books',
            image: '/images/p14.jpg',
            price:17,
            rating:4.0,
            numReviews:30,
            description: 'high quality product',
        },
        {
            _id:'15',
            name: 'All-Star Superman (Grant Morrison)',
            category: 'Books',
            image: '/images/p15.jpg',
            price:22.75,
            rating:4.0,
            numReviews:40,
            description: 'high quality product',
        },
        {
            _id:'16',
            name: 'Kingdom Come (Mark Waid, Alex Ross)',
            category: 'Books',
            image: '/images/p16.jpg',
            price:24.85,
            rating:3.7,
            numReviews:41,
            description: 'high quality product',
        },
        {
            _id:'17',
            name: 'Superman: Red Son (Mark Millar)',
            category: 'Books',
            image: '/images/p17.jpg',
            price:29.95,
            rating:3.5,
            numReviews:28,
            description: 'high quality product',
        },
        {
            _id:'18',
            name: 'Persepolis (Marjane Satrapi)',
            category: 'Books',
            image: '/images/p18.jpeg',
            price:27.45,
            rating:3.9,
            numReviews:39,
            description: 'high quality product',
        },
    ]
}
export default data;